import React from "react";

import {Layout} from "antd";

const {Content} = Layout

const AppContent = props => {
    return (
        <Content
            className="site-layout-background"
            style={{
                margin: '24px 16px',
                padding: 24,
                minHeight: 280,
            }}>
            <div className="site-layout-background" style={{padding: 24, textAlign: 'center'}}>
                ...
                <br/>
                Really
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                long
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                ...
                <br/>
                content
            </div>
        </Content>
    )
}

export default AppContent;